#!/bin/bash
if [ "$1" = '-d' ]; then
  debug=$1
  shift
fi

if [ -z $1 ]; then
  app_path=./tmp
else
  app_path=~/Trike/$1/tmp
fi
echo restarting: $app_path
touch $app_path/restart.txt
if [ $debug ]; then
  touch $app_path/debug.txt
  echo debugging: on
fi
